### ISSUE TITLE
mt7620 not an available target

### ISSUE THREAD

**Issue by marvinmarnold** [libre-mesh/lime-build#14]
Is there a reason that mt7620 is [not listed](https://github.com/libremesh/lime-build/blob/16.07/targets.mk#L6) as an available target? It seems to have [behaviour](https://github.com/libremesh/lime-build/blob/16.07/targets.mk#L28) defined.

**Comment by ilario** [comment]
Looks like my commit 24e8553a9bc6e36525843ae6cc111b114d0806b2 was not included in the 16.07 release, but in develop should be fixed.

**Comment by marvinmarnold** [comment]
Thanks @ilario
