### ISSUE TITLE
 mt7621 not an available target 

### ISSUE THREAD

**Issue by ilario** [libre-mesh/lime-build#15]
This is a recurring issue as is equivalent to #14.
The mt7621 is not present in the `TARGETS_AVAILABLE` list in the `targets.mk` file.

**Comment by ilario** [comment]
This was fixed in f92c2d5 but that commit is not included in branch 17.02

**Comment by p4u** [comment]
This is the expected way of work. General changes go to development and later or merged of cherry picked to the release branches.

**Comment by p4u** [comment]
Provide a pull-request of the merging if you like.

**Comment by ilario** [comment]
This was fixed as f92c2d5 got included in 17.02 also.
