### ISSUE TITLE
Add contact info to readme

### ISSUE THREAD

**Issue by ilario** [libre-mesh/lime-build#6]
Similarly to issue [45](/libre-mesh/lime-packages/issues/45) opened on lime-packages and solved with pull request [46](/libre-mesh/lime-packages/pull/46), also here the contact information should be added to the readme.

**Comment by ilario** [comment]
Partially addressed in ac2c155, a complete solution would be something like [this](/libre-mesh/lime-packages/pull/46/commits/c0331f17e1bf9c7dc8b67727dbe8c91537528b5e).

**Comment by p4u** [comment]
Hi Ilario.

Feel free to do it yourself or send a pull request :)

Cheers.
